<script src="frontEnd/js/vendor/jquery-2.2.4.min.js"></script>
<script src="frontEnd/js/popper.min.js"></script>
<script src="frontEnd/js/vendor/bootstrap.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="frontEnd/js/jquery-ui.js"></script>
<script src="frontEnd/js/easing.min.js"></script>
<script src="frontEnd/js/hoverIntent.js"></script>
<script src="frontEnd/js/superfish.min.js"></script>
<script src="frontEnd/js/jquery.ajaxchimp.min.js"></script>
<script src="frontEnd/js/jquery.magnific-popup.min.js"></script>
<script src="frontEnd/js/jquery.nice-select.min.js"></script>
<script src="frontEnd/js/owl.carousel.min.js"></script>
<script src="frontEnd/js/mail-script.js"></script>
<script src="frontEnd/js/main.js"></script>